# fruits=[]
# f1=input("Enter the first fruit name:")
# fruits.append(f1)
# f2=input("Enter the second fruit name:")
# fruits.append(f2)
# f3=input("Enter the third fruit name:")
# fruits.append(f3)
# f4=input("Enter the fourth fruit name:")
# fruits.append(f4)
# f5=input("Enter the fifth fruit name:")
# fruits.append(f5)
# f6=input("Enter the sixth fruit name:")
# fruits.append(f6)
# f7=input("Enter the seventh fruit name:")
# fruits.append(f7)
# print(fruits)

# marks=[]
# s1=int(input("enter first student marks: "))
# marks.append(s1)
# s2=int(input("enter second student marks: "))
# marks.append(s2)
# s3=int(input("enter third student marks: "))
# marks.append(s3)
# s4=int(input("enter fourth student marks: "))
# marks.append(s4)
# s5=int(input("enter fifth student marks: "))
# marks.append(s5)
# s6=int(input("enter sixth student marks: "))
# marks.append(s6)
# marks.sort()
# print(marks)

# tuple1=(1,2,3,4,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,)
# print(tuple1.count(0))  #this will count the number of times 0 appears in the tuple
# print(tuple1.index(4))  #this will print the index of the first occurrence of 4 in the tuple

# dict ={ "hello": "namaste" , "apple": "seb", "ball": "gola" }
# dict1=input("enter the word: ")
# print(dict[dict1])

# s=set()
# n=input("enter a no : ")
# s.add(int(n))
# n=input("enter a no : ")
# s.add(int(n))
# n=input("enter a no : ")
# s.add(int(n))
# n=input("enter a no : ")
# s.add(int(n))
# n=input("enter a no : ")
# s.add(int(n))
# n=input("enter a no : ")
# s.add(int(n))
# n=input("enter a no : ")
# s.add(int(n))

# print(s)

s=set()
n=input("enter a no :")
s.add(n)
n=int(input("enter a no :"))
s.add(int(n))
print(s)